version: '3.8'

services:
  vroom:
    build:
      context: .
      dockerfile: Dockerfile.vroom
    ports:
      - '3001:3000'
    environment:
      - VROOM_DOCKER=osrm
      - VROOM_LOG=/conf
    volumes:
      - ./conf:/conf
      - ./logs:/var/log
    healthcheck:
      test: ['CMD', 'curl', '--fail', '-s', 'http://localhost:3001/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - vroom-network

networks:
  vroom-network:
    driver: bridge

volumes:
  conf:
    driver: local
  logs:
    driver: local
