---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ruttoptimering
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ruttoptimering
  policy:
    semver:
      range: 'x.x.x'

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ruttoptimering
  namespace: flux-system
spec:
  image: ghcr.io/iteam1337/ruttoptimering
  interval: 30s
  provider: generic

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ruttoptimering
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ruttoptimering
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main

  update:
    path: ./k8s
    strategy: Setters
